# Generated by Django 3.1 on 2020-10-29 23:42

from django.db import migrations, models
import draft_forms.models
import multiplefilefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('draft_forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftformstable',
            name='id',
        ),
        migrations.AlterField(
            model_name='draftformstable',
            name='findingFile',
            field=multiplefilefield.fields.MultipleFileModelField(blank=True, max_length=1000, null=True, upload_to=draft_forms.models.UploadTo('findingFile')),
        ),
        migrations.AlterField(
            model_name='draftformstable',
            name='handlingFile',
            field=multiplefilefield.fields.MultipleFileModelField(blank=True, max_length=1000, null=True, upload_to=draft_forms.models.UploadTo('handlingFile')),
        ),
        migrations.AlterField(
            model_name='draftformstable',
            name='investigationFile',
            field=multiplefilefield.fields.MultipleFileModelField(blank=True, max_length=1000, null=True, upload_to=draft_forms.models.UploadTo('investigationFile')),
        ),
        migrations.AlterField(
            model_name='draftformstable',
            name='reference',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
