# Generated by Django 3.0.6 on 2020-10-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft_forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftformstable',
            name='id',
        ),
        migrations.AlterField(
            model_name='draftformstable',
            name='reference',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
