# Generated by Django 3.2.dev20200923115826 on 2020-10-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft_forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftformstable',
            name='eventAuthorizers',
            field=models.CharField(default=[], max_length=70),
        ),
    ]
