# Generated by Django 3.0.6 on 2020-05-24 12:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnitsTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitTreeId', models.IntegerField(default=0)),
                ('maxTreeNodeId', models.IntegerField(default=0)),
                ('treeNode', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
