# Generated by Django 3.1 on 2020-05-19 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitstree',
            old_name='max_tree_node_id',
            new_name='maxTreeNodeId',
        ),
        migrations.RenameField(
            model_name='unitstree',
            old_name='tree_node',
            new_name='treeNode',
        ),
        migrations.RenameField(
            model_name='unitstree',
            old_name='unit_tree_id',
            new_name='unitTreeId',
        ),
    ]
