# Generated by Django 3.1 on 2020-05-22 01:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_constantsfields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constantsfields',
            name='equipmentMakat',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), size=None),
        ),
        migrations.AlterField(
            model_name='constantsfields',
            name='equipmentType',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), size=None),
        ),
        migrations.AlterField(
            model_name='constantsfields',
            name='eventStatus',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), size=None),
        ),
        migrations.AlterField(
            model_name='constantsfields',
            name='handlingStatus',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), size=None),
        ),
        migrations.AlterField(
            model_name='constantsfields',
            name='materialType',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), size=None),
        ),
        migrations.AlterField(
            model_name='constantsfields',
            name='rank',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), size=None),
        ),
    ]
