# Generated by Django 3.1 on 2020-05-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20200522_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='constantsfields',
            name='constantFieldId',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
