# Generated by Django 3.1 on 2020-09-03 17:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20200903_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constantsfields',
            name='equipmentType',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, null=True, size=None),
        ),
    ]
