from django.db import models


class LostForm(models.Model):
    # name = models.CharField(max_length=70, blank=False, default='')
    # age = models.IntegerField(blank=False, default=1)
    # active = models.BooleanField(default=False)
    reference = models.CharField(max_length=70, blank=False, default='')
    eventType = models.CharField(max_length=70, blank=False, default='')
    date = models.CharField(max_length=70, blank=False, default='')
    reporterName = models.CharField(max_length=70, blank=False, default='')
    reporterUnit = models.CharField(max_length=70, blank=False, default='')
    caseIdOnMetzah = models.CharField(max_length=70, blank=False, default='')
    handlingResults = models.CharField(max_length=70, blank=False, default='')
    eventStatus = models.CharField(max_length=70, blank=False, default='')
    handlingStatus = models.CharField(max_length=70, blank=False, default='')
    signerUnit = models.CharField(max_length=70, blank=False, default='')
    signerName = models.CharField(max_length=70, blank=False, default='')
    signerId = models.CharField(max_length=70, blank=False, default='')
    rank = models.CharField(max_length=70, blank=False, default='')
    position = models.CharField(max_length=70, blank=False, default='')
    eventDate = models.CharField(max_length=70, blank=False, default='')
    eventHour = models.CharField(max_length=70, blank=False, default='')
    equipment = models.CharField(max_length=70, blank=False, default='')
    equipmentType = models.CharField(max_length=70, blank=False, default='')
    equipmentMark = models.CharField(max_length=70, blank=False, default='')
    equipmentMakat = models.CharField(max_length=70, blank=False, default='')
    eventRelevantPlacesAndFactors = models.CharField(max_length=70, blank=False, default='')
    eventInitialDetails = models.CharField(max_length=70, blank=False, default='')
    investigationDate= models.CharField(max_length=70, blank=False, default='')
    investigationFile= models.CharField(max_length=70, blank=False, default='')
    handlingDate= models.CharField(max_length=70, blank=False, default='')
    findingDate= models.CharField(max_length=70, blank=False, default='')
    findingFile= models.CharField(max_length=70, blank=False, default='')
    handlingFile= models.CharField(max_length=70, blank=False, default='')
    messages= models.CharField(max_length=70, blank=False, default='')