# Generated by Django 3.1 on 2020-05-16 16:16

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LostForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.IntegerField(default=0)),
                ('eventType', models.CharField(default='', max_length=70)),
                ('date', models.CharField(default='', max_length=70)),
                ('reporterName', models.CharField(default='', max_length=70)),
                ('reporterUnit', models.CharField(default='', max_length=70)),
                ('editStateBlocked', models.BooleanField(default=True)),
                ('caseIdOnMetzah', models.CharField(default='', max_length=70)),
                ('handlingResults', models.CharField(default='', max_length=70)),
                ('eventStatus', models.CharField(default='', max_length=70)),
                ('handlingStatus', models.CharField(default='', max_length=70)),
                ('signerUnit', models.CharField(default='', max_length=70)),
                ('signerName', models.CharField(default='', max_length=70)),
                ('signerId', models.CharField(default='', max_length=70)),
                ('rank', models.CharField(default='', max_length=70)),
                ('position', models.CharField(default='', max_length=70)),
                ('eventDate', models.CharField(default='', max_length=70)),
                ('eventHour', models.CharField(default='', max_length=70)),
                ('equipment', models.CharField(default='', max_length=70)),
                ('equipmentType', models.CharField(default='', max_length=70)),
                ('equipmentMark', models.CharField(default='', max_length=70)),
                ('equipmentMakat', models.CharField(default='', max_length=70)),
                ('eventRelevantPlacesAndFactors', models.CharField(default='', max_length=70)),
                ('eventInitialDetails', models.CharField(default='', max_length=70)),
                ('investigationDate', models.CharField(default='', max_length=70)),
                ('investigationFile', models.FileField(blank=True, null=True, upload_to=customers.models.UploadTo('investigationFile'))),
                ('handlingDate', models.CharField(default='', max_length=70)),
                ('findingDate', models.CharField(default='', max_length=70)),
                ('findingFile', models.FileField(blank=True, null=True, upload_to=customers.models.UploadTo('findingFile'))),
                ('handlingFile', models.FileField(blank=True, null=True, upload_to=customers.models.UploadTo('handlingFile'))),
                ('messages', models.CharField(default='', max_length=70)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
