# Generated by Django 3.1 on 2020-04-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default='', max_length=70)),
                ('eventType', models.CharField(default='', max_length=70)),
                ('date', models.CharField(default='', max_length=70)),
                ('reporterName', models.CharField(default='', max_length=70)),
                ('reporterUnit', models.CharField(default='', max_length=70)),
                ('caseIdOnMetzah', models.CharField(default='', max_length=70)),
                ('handlingResults', models.CharField(default='', max_length=70)),
                ('eventStatus', models.CharField(default='', max_length=70)),
                ('handlingStatus', models.CharField(default='', max_length=70)),
                ('signerUnit', models.CharField(default='', max_length=70)),
                ('signerName', models.CharField(default='', max_length=70)),
                ('signerId', models.CharField(default='', max_length=70)),
                ('rank', models.CharField(default='', max_length=70)),
                ('position', models.CharField(default='', max_length=70)),
                ('eventDate', models.CharField(default='', max_length=70)),
                ('eventHour', models.CharField(default='', max_length=70)),
                ('equipment', models.CharField(default='', max_length=70)),
                ('equipmentType', models.CharField(default='', max_length=70)),
                ('equipmentMark', models.CharField(default='', max_length=70)),
                ('equipmentMakat', models.CharField(default='', max_length=70)),
                ('eventRelevantPlacesAndFactors', models.CharField(default='', max_length=70)),
                ('eventInitialDetails', models.CharField(default='', max_length=70)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
