# Generated by Django 3.1 on 2020-05-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formstable',
            name='isMatchToReport',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='formstable',
            name='editStateBlocked',
            field=models.BooleanField(default=False),
        ),
    ]
