# Generated by Django 3.1 on 2020-05-06 21:49

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20200426_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostform',
            name='findingFile',
            field=models.FileField(blank=True, upload_to=customers.models.UploadTo('findingFile')),
        ),
        migrations.AlterField(
            model_name='lostform',
            name='handlingFile',
            field=models.FileField(blank=True, upload_to=customers.models.UploadTo('handlingFile')),
        ),
        migrations.AlterField(
            model_name='lostform',
            name='investigationFile',
            field=models.FileField(blank=True, upload_to=customers.models.UploadTo('investigationFile')),
        ),
        migrations.AlterField(
            model_name='lostform',
            name='reference',
            field=models.IntegerField(default=0),
        ),
    ]
