# Generated by Django 3.1 on 2020-05-15 23:07

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20200507_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostform',
            name='editState',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lostform',
            name='findingFile',
            field=models.FileField(blank=True, null=True, upload_to=customers.models.UploadTo('findingFile')),
        ),
        migrations.AlterField(
            model_name='lostform',
            name='handlingFile',
            field=models.FileField(blank=True, null=True, upload_to=customers.models.UploadTo('handlingFile')),
        ),
        migrations.AlterField(
            model_name='lostform',
            name='investigationFile',
            field=models.FileField(blank=True, null=True, upload_to=customers.models.UploadTo('investigationFile')),
        ),
    ]
