# Generated by Django 3.1 on 2020-05-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20200516_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lostform',
            name='editState',
        ),
        migrations.AddField(
            model_name='lostform',
            name='editStateBlocked',
            field=models.BooleanField(default=True),
        ),
    ]
