# Generated by Django 3.1 on 2020-10-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='msgs',
            name='reporterUnit',
            field=models.CharField(default='', max_length=70),
        ),
    ]
