# Generated by Django 3.1 on 2020-10-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0002_msgs_reporterunit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msgs',
            name='id',
        ),
        migrations.AlterField(
            model_name='msgs',
            name='reference',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
