# Generated by Django 3.0.5 on 2020-09-22 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0002_auto_20200914_1437'),
        ('msgs', '0002_auto_20200914_1424'),
    ]

    operations = [
    ]
