# Generated by Django 3.0.6 on 2020-09-02 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsEquipments',
            fields=[
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='equipments', serialize=False, to='forms.FormsTable', unique=True)),
                ('equipment', models.CharField(default='', max_length=70)),
                ('equipmentType', models.CharField(default='', max_length=70)),
                ('equipmentMark', models.CharField(default='', max_length=70)),
                ('equipmentMakat', models.CharField(default='', max_length=70)),
            ],
        ),
        migrations.DeleteModel(
            name='EventsEquipment',
        ),
    ]
