# Generated by Django 3.1 on 2020-06-16 18:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formstable',
            name='messages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=['', ''], max_length=150), size=100),
        ),
    ]
