# Generated by Django 3.0.6 on 2020-09-02 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20200902_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsequipments',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='equipments', serialize=False, to='forms.FormsTable'),
        ),
    ]
