# Generated by Django 3.1 on 2020-06-16 18:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20200616_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formstable',
            name='messages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=150, null=True), blank=True, null=True, size=100),
        ),
    ]
