# Generated by Django 3.0.5 on 2020-06-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200621_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='armyposistion',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='destination',
            name='armyunit',
            field=models.CharField(default=' ', max_length=150),
        ),
        migrations.AlterField(
            model_name='destination',
            name='firstname',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='destination',
            name='lastname',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='destination',
            name='password',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='destination',
            name='permissions',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='destination',
            name='personalnumber',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='destination',
            name='rank',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='destination',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
    ]
